name: Gradle Wrapper updates checker
on:
  workflow_dispatch:
  schedule:
  #  - cron: "0 00 * * *"
    - cron: "0-59/7 * * * *"
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Gradle Wrapper updates
        uses: gradle-update/update-gradle-wrapper-action@v1.0.14
      - name: Check for Gradle Wrapper updates 2
        uses: MeilCli/gradle-update-check-action@v3.0.0
