name: Gradle Wrapper updates checker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gradle-wrapper:
    name: Gradle Wrapper updates checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Check for Gradle Wrapper updates
        uses: gradle-update/update-gradle-wrapper-action@v1.0.14
      - name: Gradle validation
        uses: gradle/wrapper-validation-action@v1.0.4
